rules:
  - name: Opstooling
    condition:
      include:
        - '.*'
      exclude: 
        - 'README.md'
    type: basic
    teams:
      - opstooling
  - name: Config file
    condition:
      include:
        - 'review-bot.yml'
    type: and-distinct
    countAuthor: true
    reviewers:
      - teams:
        - opstooling
      - users:
        - mordamax
        - mutantcornholio
        - rzadp
        - bullrich
