name: "Review Bot"
description: "Have custom review rules for PRs with auto assignment"
author: paritytech
branding:
  icon: zoom-in
  color: red
inputs:
  repo-token:
    required: true
    description: The token to access the repo and the pull request data
  team-token:
    required: true
    description: A GitHub Token with read:org access
  config-file:
    description: 'Location of the configuration file'
    required: false
    default: '.github/review-bot.yml'
outputs:
  repo:
    description: 'The name of the repo in owner/repo pattern'
  

runs:
  using: 'docker'
  image: 'Dockerfile'
