name: "Review Bot"
description: "Have custom review rules for PRs with auto assignment"
author: paritytech
branding:
  icon: zoom-in
  color: red
inputs:
  GITHUB_TOKEN:
    required: true
    description: The token to access the repo
  config-file:
    description: 'Location of the configuration file'
    required: false
    default: '.github/review.yml'
outputs:
  repo:
    description: 'The name of the repo in owner/repo pattern'
  

runs:
  using: 'docker'
  image: 'Dockerfile'
