name: Continuous testing

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        command: [lint, build, test, "cli '.github/review-bot.yml'"]
    runs-on: ubuntu-latest
    name: running ${{ matrix.command }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4.0.2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run ${{ matrix.command }}

  conclude:
    runs-on: ubuntu-latest
    name: All tests passed
    needs: [test]
    steps:
      - run: echo '### Good job! All the tests passed 🚀' >> $GITHUB_STEP_SUMMARY
