name: Continuous testing

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run lint

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run build

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run test
