name: Continuous testing

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: deps
          path: node_modules

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get dependencies
        uses: actions/download-artifact@v2
        with:
          name: deps
          path: node_modules
      - run: yarn run lint
      
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get dependencies
        uses: actions/download-artifact@v2
        with:
          name: deps
          path: node_modules
      - run: yarn run build

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get dependencies
        uses: actions/download-artifact@v2
        with:
          name: deps
          path: node_modules
      - run: yarn run test
